module.exports = 
{
    TICKETMASTER_API_KEY: process.env.TICKETMASTER_API_KEY,
    YELP_API_KEY: process.env.YELP_API_KEY,
    YELP_CLIENT_ID: process.env.YELP_CLIENT_ID,
    TWITTER_CONSUMER_KEY: process.env.TWITTER_CONSUMER_KEY, 
    TWITTER_CONSUMER_SECRET: process.env.TWITTER_CONSUMER_SECRET,
    TWITTER_ACCESS_TOKEN: process.env.TWITTER_ACCESS_TOKEN,
    TWITTER_TOKEN_SECRET: process.env.TWITTER_TOKEN_SECRET
}